controller_list:
  - name: fake_left_arm_controller
    type: $(arg execution_type)
    joints:
      - joint_D6
      - joint_D7
      - joint_D8
      - joint_D9
      - joint_D10
      - joint_EE_L
  - name: fake_right_arm_controller
    type: $(arg execution_type)
    joints:
      - joint_D11
      - joint_D12
      - joint_D13
      - joint_D14
      - joint_D15
      - joint_EE
  - name: fake_right_hand_controller
    type: $(arg execution_type)
    joints:
      - joint_EE
  - name: fake_left_hand_controller
    type: $(arg execution_type)
    joints:
      - joint_EE_L
initial:  # Define initial robot poses.
  - group: left_arm
    pose: neutral_left
  - group: right_arm
    pose: neutral_right