(cl:in-package open_manipulator_core-msg)
(cl:export '(DXL_ID-VAL
          DXL_ID
          PRESENT_TEMP-VAL
          PRESENT_TEMP
          PRESENT_LOAD-VAL
          PRESENT_LOAD
          PRESENT_VOLT-VAL
          PRESENT_VOLT
          PRESENT_CURRENT-VAL
          PRESENT_CURRENT
          PRESENT_POS-VAL
          PRESENT_POS
          PRESENT_VEL-VAL
          PRESENT_VEL
          GOAL_POS-VAL
          GOAL_POS
          GOAL_VEL-VAL
          GOAL_VEL
          RETURN_DELAY_TIME-VAL
          RETURN_DELAY_TIME
          FEEDFORWARD_1ST_GAIN-VAL
          FEEDFORWARD_1ST_GAIN
          FEEDFORWARD_2ND_GAIN-VAL
          FEEDFORWARD_2ND_GAIN
          ERROR_STATUS-VAL
          ERROR_STATUS
          TEMP_LIMIT-VAL
          TEMP_LIMIT
          POS_P_GAIN-VAL
          POS_P_GAIN
          POS_I_GAIN-VAL
          POS_I_GAIN
          POS_D_GAIN-VAL
          POS_D_GAIN
          VEL_P_GAIN-VAL
          VEL_P_GAIN
          VEL_I_GAIN-VAL
          VEL_I_GAIN
))