controller_list:
  - name: fake_left_arm_controller
    type: $(arg execution_type)
    joints:
      - joint_D6
      - joint_D7
      - joint_D8
      - joint_D9
      - joint_D10
      - joint_EE
initial:  # Define initial robot poses.
  - group: left_arm
    pose: neutral