# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: left_arm
  joint_model_group_pose: neutral_left
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_D11
    - joint_D12
    - joint_D13
    - joint_D14
    - joint_D15
    - joint_EE
    - joint_D6
    - joint_D7
    - joint_D8
    - joint_D9
    - joint_D10
    - joint_EE_L
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_D6
      - joint_D7
      - joint_D8
      - joint_D9
      - joint_D10
      - joint_EE_L
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_D11
      - joint_D12
      - joint_D13
      - joint_D14
      - joint_D15
      - joint_EE
  - name: right_hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      joint_EE
  - name: left_hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      joint_EE_L
abel_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_D6
    - joint_D7
    - joint_D8
    - joint_D9
    - joint_D10
    - joint_EE_L
    - joint_D11
    - joint_D12
    - joint_D13
    - joint_D14
    - joint_D15
    - joint_EE
  gains:
    joint_D6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_D7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_D8:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_D9:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_D10:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_EE_L:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_D11:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_D12:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_D13:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_D14:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_D15:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_EE:
      p: 100
      d: 1
      i: 1
      i_clamp: 1